### ISSUE TITLE
Support Configuration from CLI

### ISSUE THREAD

**Issue by ChristianMurphy** [Swatinem/esgraph#14]
Support setting esgraph options and espree options when using the command line interface.
This could be done using command line flags and/or a configuration file.

**Comment by ChristianMurphy** [comment]
I'd lean toward using a configuration file for the first iteration, then adding flags down the road.
I'm looking at https://github.com/davidtheclark/cosmiconfig to handle file based configuration, but am open to other technologies.

**Comment by Swatinem** [comment]
Not sure if its worth the effort, but doing this and #15, we might even split this up into a `-cli` package and a normal package, so library users dont have all the npm bloat.

**Comment by ChristianMurphy** [comment]
> Not sure if its worth the effort

So my thinking here is that Espree supports multiple parsing modes. E.G.
Language version ES3-ES9
Source types: script vs module
And ECMA script extentions/features: JSX, Object spread

I'd like to move toward a place where those features be parsed and a CFG can be generated, without needing to write a new CLI.

My thought was to offer a parser configuration similar to ESLint to allow switching these options.
Long term the configuration could allow enabling or disabling features within ESGraph itself.

I'm open to other approaches to handling this, or alternatives where configuration is not needed at all.
Thoughts are welcome :thought_balloon: 

> we might even split this up into a `-cli` package and a normal package, so library users dont have all the npm bloat.

Yeah, if this approach is the direction decided on splitting out `cli` would give library only users some good savings.

**Comment by ChristianMurphy** [comment]
closing this out as a non-priority
