### ISSUE TITLE
Does it need to create a new node for SwitchStatement

### ISSUE THREAD

**Issue by chengfulin** [Swatinem/esgraph#5]
Hello,
I have thought that if there is a node for SwitchStatement, then we can obviously find out there is a use at that node. Or, are there something I have to concern but I missed?

Thanks.
Sincerely yours.

**Comment by Swatinem** [comment]
I don’t really understand your question here. What is your use case?

**Comment by chengfulin** [comment]
For the case written below, if I do the def-use analysis for it, e.g., find the DU pairs for variable <code>test</code>), I would miss the use at the <code>SwitchStatement</code> because there isn't a node in the CFG. Or, the uses should be located at those nodes represent <code>SwitchCase</code> in AST?
```javascript
var test = 3, out;
switch (test) {
case 1:
    out = test;
    break;
case 2:
    out = test * test;
    break;
case 3:
    out = test * test * test;
    break;
case 4:
case 5:
    out = 0;
    break;
default:
    out = -1;
}
var tmp = out;
```

**Comment by Swatinem** [comment]
Ah now I understand.

What I tried to do was to desugar SwitchCase into a series of if-like branches, with the fallthroughs and breaks hooked up correctly.

It does the second part, modeling the control flow, correctly, but it misses the first part.

So essentially each `SwitchCase` should become a `BinaryExpression`.

Similar to this:
![switchcase](https://cloud.githubusercontent.com/assets/580492/7135242/ed00ac2a-e2a4-11e4-907e-130c45377463.png)

(in the example there are a lot of exception edges, I would have to read up on them to figure out if thats also the case for the SwitchCase statement or not)

**Comment by Swatinem** [comment]
You should have access to the parent SwitchStatement via `.parent` though.

**Comment by chengfulin** [comment]
Thanks, I could figure out how it works and how to use it to find the information I need.
