### ISSUE TITLE
Npm is outdated

### ISSUE THREAD

**Issue by one000mph** [Swatinem/esgraph#7]
It seems that the version of esgraph in npm is outdated. In bin/esgraph.js we still have
`
	function handleFunction(recurse) {
		functions.push(this);
		recurse(this.body);
	}
`
rather than the correct version (in github)
`
function handleFunction(node, recurse) {
		functions.push(node);
		recurse(node.body);
	}
`
Can you update this please? This error took me a long time to diagnose and it was really just a version issue. Thanks.

**Comment by Swatinem** [comment]
Just released 0.2.0 (and 0.2.1 because I forgot to pull, haha)
